USE [Photography Chain]
GO
	--DROP TABLE Discount
	DROP TABLE if exists USP_Database_Version
	DROP TABLE if exists Database_Version
	DROP TABLE if exists Works_at
	DROP TABLE if exists Is_Avaible_At
	DROP TABLE if exists Buys_From
	DROP TABLE if exists Gets_Products_From
	DROP TABLE if exists Event
	DROP TABLE if exists Suplier
	DROP TABLE if exists Client
	DROP TABLE if exists Shop
	DROP TABLE if exists Employee
	DROP TABLE if exists Manager
	DROP TABLE if exists Product
	
GO

CREATE TABLE USP_Database_Version(
	USP_UP VARCHAR(50) UNIQUE,
	USP_DOWN VARCHAR(50) UNIQUE,
	TARGET_VERSION INT
);

CREATE TABLE Database_Version(
	CURRENT_VERSION INT DEFAULT 0
);

CREATE TABLE Manager
(
	MANAGER_ID INT PRIMARY KEY,
	MANAGER_NAME VARCHAR(50),
	MANAGER_SALARY int
);

CREATE TABLE Employee
(
	EMPLOYEE_ID INT PRIMARY KEY,
	EMPLOYEE_NAME VARCHAR(50),
	EMPLOYEE_SALARY INT,
	MANAGER_ID INT,
	FOREIGN KEY(MANAGER_ID) REFERENCES Manager(MANAGER_ID)
);

CREATE TABLE Shop(
	SHOP_ID INT PRIMARY KEY,
	SHOP_LOCATION VARCHAR(100),
	MANAGER_ID INT UNIQUE,
	FOREIGN KEY(MANAGER_ID) REFERENCES Manager(MANAGER_ID),
);

CREATE TABLE Event
(
	EVENT_ID int PRIMARY KEY,
	EVENT_DATE VARCHAR(10),
	EVENT_VALUE int
);

CREATE TABLE  Works_at
(
	EVENT_ID int,
	EMPLOYEE_ID int,
	FOREIGN KEY(EVENT_ID) REFERENCES Event(EVENT_ID),
	FOREIGN key(EMPLOYEE_ID) REFERENCES Employee(EMPLOYEE_ID),
	Constraint WORKS_AT_ID Primary KEy(EVENT_ID,EMPLOYEE_ID)
);

CREATE TABLE Product(
	PRODUCT_ID INT PRIMARY KEY,
	PRODUCT_PRICE INT
)

CREATE TABLE Is_Avaible_At
(
	PRODUCT_ID INT,
	SHOP_ID INT,
    FOREIGN KEY (PRODUCT_ID) REFERENCES Product(PRODUCT_ID),
    FOREIGN KEY (SHOP_ID) REFERENCES Shop(SHOP_ID),
	CONSTRAINT IS_AVAIBLE_AT_ID Primary KEY(SHOP_ID,PRODUCT_ID)
);

CREATE TABLE Client
(
	CLIENT_ID INT PRIMARY KEY,
	CLIENT_NAME VARCHAR(50),
	CLIENT_PHONE_NUMBER VARCHAR(20)
);

CREATE TABLE Buys_From
(
	CLIENT_ID INT,
	SHOP_ID INT,
	FOREIGN KEY (SHOP_ID) REFERENCES Shop(SHOP_ID),
	FOREIGN KEY (CLIENT_ID) REFERENCES Client(CLIENT_ID),
	CONSTRAINT Buys_From_ID PRIMARY KEY (CLIENT_ID, SHOP_ID)
);

CREATE TABLE Suplier
(
	SUPLIER_ID INT PRIMARY KEY,
	SUPLIER_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE Gets_Products_From
(
	SUPLIER_ID INT,
	SHOP_ID INT,
	FOREIGN KEY(SHOP_ID) REFERENCES Shop(SHOP_ID),
	FOREIGN KEY(SUPLIER_ID) REFERENCES Suplier(SUPLIER_ID),
	Constraint GETS_PROUCTS_FROM_ID Primary KEy(SUPLIER_ID,SHOP_ID)
);
