/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-05-07 18:10:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import registration.models.Profile;
import java.util.List;
import java.sql.SQLException;
import registration.data_access_object.ProfileDAO;

public final class profile_005fdetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("registration.models.Profile");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.sql.SQLException");
    _jspx_imports_classes.add("registration.data_access_object.ProfileDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Profile Details</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        .header {\r\n");
      out.write("            background-color: #333;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: row;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .wlecome-message{\r\n");
      out.write("            color: #4CAF50;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .header button {\r\n");
      out.write("            vertical-align: middle;\r\n");
      out.write("            background-color: #4CAF50;\r\n");
      out.write("            border: none;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            transition-duration: 0.4s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .header button:hover {\r\n");
      out.write("            background-color: #45a049;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Added style for logout button */\r\n");
      out.write("        .logout-button {\r\n");
      out.write("            margin-left: 10px;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Modal */\r\n");
      out.write("        .modal {\r\n");
      out.write("            display: none; /* Hidden by default */\r\n");
      out.write("            position: fixed; /* Stay in place */\r\n");
      out.write("            z-index: 1; /* Sit on top */\r\n");
      out.write("            left: 0;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            overflow: auto;\r\n");
      out.write("            background-color: rgba(0,0,0,0.4);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .modal-content {\r\n");
      out.write("            background-color: #fefefe;\r\n");
      out.write("            margin: 15% auto;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            border: 1px solid #888;\r\n");
      out.write("            width: 80%; /* Could be more or less, depending on screen size */\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Close button */\r\n");
      out.write("        .close {\r\n");
      out.write("            color: #aaa;\r\n");
      out.write("            float: right;\r\n");
      out.write("            font-size: 28px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .close:hover,\r\n");
      out.write("        .close:focus {\r\n");
      out.write("            color: black;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-form {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-form label {\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-form input[type=\"text\"] {\r\n");
      out.write("            padding: 8px;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            width: 200px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-form .search-button {\r\n");
      out.write("            background-color: #4CAF50;\r\n");
      out.write("            border: none;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            transition-duration: 0.4s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-form .search-button:hover {\r\n");
      out.write("            background-color: #45a049;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .profile-details {\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-details table {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border-collapse: collapse;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-details table td,\r\n");
      out.write("        .profile-details table th {\r\n");
      out.write("            border: 1px solid #ddd;\r\n");
      out.write("            padding: 8px;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-details table th {\r\n");
      out.write("            background-color: #f2f2f2;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-details table tr:nth-child(even) {\r\n");
      out.write("            background-color: #f2f2f2;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-details table tr:hover {\r\n");
      out.write("            background-color: #ddd;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        /* Search results section */\r\n");
      out.write("        .search-results {\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-results h2 {\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-results table {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border-collapse: collapse;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-results table th,\r\n");
      out.write("        .search-results table td {\r\n");
      out.write("            border: 1px solid #ddd;\r\n");
      out.write("            padding: 8px;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-results table th {\r\n");
      out.write("            background-color: #f2f2f2;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-results table tr:nth-child(even) {\r\n");
      out.write("            background-color: #f2f2f2;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-results table tr:hover {\r\n");
      out.write("            background-color: #ddd;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-results p {\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("            font-style: italic;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .profile-details ul {\r\n");
      out.write("            list-style-type: none;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-details li {\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            color: #4CAF50;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-details li strong {\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("    <form id=\"logoutForm\" action=\"");
      out.print( request.getContextPath() );
      out.write("/logoutServlet\" method=\"post\">\r\n");
      out.write("        <button class=\"logout-button\" type=\"submit\">Logout</button>\r\n");
      out.write("    </form>\r\n");
      out.write("    ");

        // Retrieve the Profile object from the session
        Profile loggedInProfile = (Profile) session.getAttribute("loggedInProfile");
    
      out.write("\r\n");
      out.write("    <span class=\"wlecome-message\">Welcome, ");
      out.print( loggedInProfile.getUsername() );
      out.write("!</span>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Modal -->\r\n");
      out.write("<div id=\"successModal\" class=\"modal\">\r\n");
      out.write("    <!-- Modal content -->\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("        <span class=\"close\">&times;</span>\r\n");
      out.write("        <h2>Logged in successfully</h2>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    var modal = document.getElementById(\"successModal\");\r\n");
      out.write("\r\n");
      out.write("    var span = document.getElementsByClassName(\"close\")[0];\r\n");
      out.write("\r\n");
      out.write("    var loginSuccess = '");
      out.print( session.getAttribute("loginSuccess") );
      out.write("';\r\n");
      out.write("\r\n");
      out.write("    if (loginSuccess === 'true') {\r\n");
      out.write("        modal.style.display = \"block\";\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    span.onclick = function() {\r\n");
      out.write("        modal.style.display = \"none\";\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    window.onclick = function(event) {\r\n");
      out.write("        if (event.target == modal) {\r\n");
      out.write("            modal.style.display = \"none\";\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"profile-details\">\r\n");
      out.write("    <ul>\r\n");
      out.write("        <li><strong>Email:</strong> ");
      out.print( loggedInProfile.getEmail() );
      out.write("</li>\r\n");
      out.write("        <li><strong>Image:</strong> ");
      out.print( loggedInProfile.getImage() );
      out.write("</li>\r\n");
      out.write("        <li><strong>Age:</strong> ");
      out.print( loggedInProfile.getAge() );
      out.write("</li>\r\n");
      out.write("        <li><strong>Home:</strong> ");
      out.print( loggedInProfile.getHome() );
      out.write("</li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"search-form\">\r\n");
      out.write("    <form action=\"\" method=\"GET\">\r\n");
      out.write("        <label for=\"username\">Search by Username:</label>\r\n");
      out.write("        <input type=\"text\" id=\"username\" name=\"username\">\r\n");
      out.write("        <input class=\"search-button\" type=\"submit\" value=\"Search\">\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"search-form\">\r\n");
      out.write("    <form action=\"\" method=\"GET\">\r\n");
      out.write("        <label for=\"email\">Search by email:</label>\r\n");
      out.write("        <input type=\"text\" id=\"email\" name=\"email\">\r\n");
      out.write("        <input class=\"search-button\" type=\"submit\" value=\"Search\">\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"search-results\">\r\n");
      out.write("    ");

        ProfileDAO profileDAO = new ProfileDAO();
        String username = request.getParameter("username");
        String email = request.getParameter("email");

        if ((username != null && !username.isEmpty()) || (email != null && !email.isEmpty())) {

            List<Profile> searchResults = null;
            try {
                //if (!username.isEmpty()) {
                searchResults = profileDAO.getProfilesByUsername(username);
//                } else if (!email.isEmpty()) {
//                    searchResults = profileDAO.getProfilesByEmail(email);
//                }
            } catch (ClassNotFoundException | SQLException e) {
                e.printStackTrace();
            }

            if (searchResults != null && !searchResults.isEmpty()) {
    
      out.write("\r\n");
      out.write("    <h2>Search Results:</h2>\r\n");
      out.write("    <table>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <th>Username</th>\r\n");
      out.write("            <th>Email</th>\r\n");
      out.write("            <th>Image</th>\r\n");
      out.write("            <th>Age</th>\r\n");
      out.write("            <th>Home</th>\r\n");
      out.write("        </tr>\r\n");
      out.write("        ");
 for (Profile profile : searchResults) { 
      out.write("\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>");
      out.print( profile.getUsername() );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print( profile.getEmail() );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print( profile.getImage() );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print( profile.getAge() );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print( profile.getHome() );
      out.write("</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </table>\r\n");
      out.write("    ");

    } else {
    
      out.write("\r\n");
      out.write("    <p>No matching profiles found.</p>\r\n");
      out.write("    ");

            }
        }
    
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
